### ISSUE TITLE
Add git tags

### ISSUE THREAD

**Issue by pvnr0082t** [svenanders/Rantjs#11]
Hi @svenanders ,
We are [cdnjs](https://github.com/cdnjs/cdnjs) team.
Because we prefer to use `dist` folder and the name with meaning, we decide to grab files from GitHub instead of npm.
But the git auto-updater in cdnjs relied on __[git tags](https://git-scm.com/book/en/v2/Git-Basics-Tagging)__ so that it can recognize the correct version and automatically update the repo. 
Could you please add git tags for the repo? Thank you.

https://github.com/cdnjs/cdnjs/issues/7698
https://github.com/cdnjs/cdnjs/pull/8343

**Comment by svenanders** [comment]
Hi! Ok, will do! Is it alright if I tag the releases with the npm version number?

**Comment by pvnr0082t** [comment]
Yeah, that would be nice.

**Comment by svenanders** [comment]
Tags added!

**Comment by pvnr0082t** [comment]
Thank you. @svenanders :facepunch:
